services:
  database:
    extends:
      file: ./db/Backend/docker-compose.yml
      service: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306

  backend:
    extends:
      file: ./backend/docker/docker-compose.yml
      service: backend
    depends_on:
      - database
    ports:
      - ${BACKEND_HOST_PORT}:5001
