services:
  database:
    extends:
      file: ./db/docker-compose.yml
      service: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticketsystem_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    extends:
      file: ./backend/docker/docker-compose.yml
      service: app
    ports:
      - "80:5000"
